# Generated by Django 3.0.3 on 2020-02-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('detail2', models.CharField(max_length=100)),
                ('god1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='god1', to='myth.Being')),
                ('god2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='god2', to='myth.Being')),
            ],
        ),
    ]
