# Generated by Django 3.0.3 on 2020-02-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0003_god_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='being',
            name='origin',
            field=models.TextField(blank=True),
        ),
    ]
