# Generated by Django 3.0.3 on 2020-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0004_auto_20200216_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='being',
            name='associated_city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='being',
            name='origin',
            field=models.TextField(),
        ),
    ]
