# Generated by Django 3.0.3 on 2020-02-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0006_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.TextField(),
        ),
    ]
