# Generated by Django 3.0.3 on 2020-02-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0009_auto_20200218_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='god',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='myth.Being'),
        ),
    ]
