# Generated by Django 3.0.3 on 2020-02-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0010_story_god'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaveStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='myth.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggedon', to='myth.Author')),
            ],
        ),
        migrations.CreateModel(
            name='FaveGod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being', to='myth.Being')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='myth.Author')),
            ],
        ),
    ]
