# Generated by Django 3.0.3 on 2020-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myth', '0011_favegod_favestory'),
    ]

    operations = [
        migrations.AddField(
            model_name='favegod',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favestory',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
