# Generated by Django 3.0.3 on 2020-02-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myth', '0012_auto_20200218_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favegod',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='favestory',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='favegod',
            name='god',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='being', to='myth.Being'),
        ),
        migrations.AlterField(
            model_name='favegod',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='myth.Author'),
        ),
        migrations.AlterField(
            model_name='favestory',
            name='story',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='myth.Story'),
        ),
        migrations.AlterField(
            model_name='favestory',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loggedon', to='myth.Author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrtten_by', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_story', to='myth.Story')),
            ],
        ),
    ]
